version: "3.9"

services:
    api:
        build: .
        ports:
            - "5671:5671"
        volumes:
            - .env:/app/.env
        depends_on:
            - db
    db:
        image: postgres
        ports:
            - "5672:5432"
        environment:
            POSTGRES_PASSWORD: postgres
        volumes:
            - db_data:/var/lib/postgresql/data
            - ./src/main/resources/sql:/docker-entrypoint-initdb.d

volumes:
    db_data: